Repository moka-team/mokaform-server, pull requests merged in 2022-10, with the labels that each got.

#1 서버 로컬 회원가입 API 구현 (MOKA-48)
  build.gradle
  src/main/java/com/mokaform/mokaformserver/common/config/WebSecurityConfig.java
  src/main/java/com/mokaform/mokaformserver/user/controller/UserController.java
  src/main/java/com/mokaform/mokaformserver/user/domain/User.java
  src/main/java/com/mokaform/mokaformserver/user/dto/request/SignupRequest.java
  src/main/java/com/mokaform/mokaformserver/user/repository/UserRepository.java
  src/main/java/com/mokaform/mokaformserver/user/service/UserService.java
Labels: request review

#4 feat: Survey에 summary column 추가
  src/main/java/com/mokaform/mokaformserver/survey/domain/Survey.java
  src/main/java/com/mokaform/mokaformserver/survey/dto/request/SurveyCreateRequest.java
  src/main/java/com/mokaform/mokaformserver/survey/service/SurveyService.java
Labels: request review

#6 feat: 답변 저장 구현
  src/main/java/com/mokaform/mokaformserver/answer/controller/AnswerController.java
  src/main/java/com/mokaform/mokaformserver/answer/domain/Answer.java
  src/main/java/com/mokaform/mokaformserver/answer/domain/EssayAnswer.java
  src/main/java/com/mokaform/mokaformserver/answer/domain/MultipleChoiceAnswer.java
  src/main/java/com/mokaform/mokaformserver/answer/domain/OXAnswer.java
  src/main/java/com/mokaform/mokaformserver/answer/dto/request/AnswerCreateRequest.java
  src/main/java/com/mokaform/mokaformserver/answer/dto/response/AnswerCreateResponse.java
  src/main/java/com/mokaform/mokaformserver/answer/repository/AnswerRepository.java
  src/main/java/com/mokaform/mokaformserver/answer/repository/EssayAnswerRepository.java
  src/main/java/com/mokaform/mokaformserver/answer/repository/MultipleChoiceAnswerRepository.java
  src/main/java/com/mokaform/mokaformserver/answer/repository/OXAnswerRepository.java
  src/main/java/com/mokaform/mokaformserver/answer/service/AnswerService.java
Labels: request review

#7 설문 상세 조회 API 구현 (MOKA-58)
  src/main/java/com/mokaform/mokaformserver/common/exception/errorcode/CommonErrorCode.java
  src/main/java/com/mokaform/mokaformserver/survey/controller/SurveyController.java
  src/main/java/com/mokaform/mokaformserver/survey/domain/Survey.java
  src/main/java/com/mokaform/mokaformserver/survey/dto/response/MultipleChoiceQuestionResponse.java
  src/main/java/com/mokaform/mokaformserver/survey/dto/response/QuestionResponse.java
  src/main/java/com/mokaform/mokaformserver/survey/dto/response/SurveyDetailsResponse.java
  src/main/java/com/mokaform/mokaformserver/survey/dto/response/SurveyResponse.java
  src/main/java/com/mokaform/mokaformserver/survey/repository/MultiChoiceQuestionRepository.java
  src/main/java/com/mokaform/mokaformserver/survey/repository/QuestionRepository.java
  src/main/java/com/mokaform/mokaformserver/survey/repository/SurveyRepository.java
  src/main/java/com/mokaform/mokaformserver/survey/service/SurveyService.java
Labels: question, request review

#8 공개된 설문 목록 조회 API 구현 (MOKA-66)
  src/main/java/com/mokaform/mokaformserver/common/exception/errorcode/SurveyErrorCode.java
  src/main/java/com/mokaform/mokaformserver/common/response/PageResponse.java
  src/main/java/com/mokaform/mokaformserver/common/util/QuerydslCustomUtils.java
  src/main/java/com/mokaform/mokaformserver/survey/controller/SurveyController.java
  src/main/java/com/mokaform/mokaformserver/survey/dto/mapping/SurveyInfoMapping.java
  src/main/java/com/mokaform/mokaformserver/survey/dto/response/SurveyInfoResponse.java
  src/main/java/com/mokaform/mokaformserver/survey/repository/SurveyCustomRepository.java
  src/main/java/com/mokaform/mokaformserver/survey/repository/SurveyCustomRepositoryImpl.java
  src/main/java/com/mokaform/mokaformserver/survey/repository/SurveyRepository.java
  src/main/java/com/mokaform/mokaformserver/survey/repository/enums/SurveySortType.java
  src/main/java/com/mokaform/mokaformserver/survey/service/SurveyService.java
Labels: request review

#9 설문 생성 API에 설문 카테고리 추가 (MOKA-68)
  src/main/java/com/mokaform/mokaformserver/survey/domain/Survey.java
  src/main/java/com/mokaform/mokaformserver/survey/domain/SurveyCategory.java
  src/main/java/com/mokaform/mokaformserver/survey/dto/request/SurveyCreateRequest.java
  src/main/java/com/mokaform/mokaformserver/survey/repository/SurveyCategoryRepository.java
  src/main/java/com/mokaform/mokaformserver/survey/service/SurveyService.java
Labels: request review

#10 설문 목록 조회 API 응답값에 설문 카테고리 추가 (MOKA-69)
  src/main/java/com/mokaform/mokaformserver/survey/dto/response/SurveyInfoResponse.java
  src/main/java/com/mokaform/mokaformserver/survey/repository/SurveyCategoryRepository.java
  src/main/java/com/mokaform/mokaformserver/survey/service/SurveyService.java
Labels: request review

#11 특정 사용자가 생성한 설문 목록 조회 API 구현 (MOKA-59)
  src/main/java/com/mokaform/mokaformserver/survey/controller/SurveyController.java
  src/main/java/com/mokaform/mokaformserver/survey/repository/SurveyCustomRepository.java
  src/main/java/com/mokaform/mokaformserver/survey/repository/SurveyCustomRepositoryImpl.java
  src/main/java/com/mokaform/mokaformserver/survey/service/SurveyService.java
  src/main/java/com/mokaform/mokaformserver/user/controller/UserController.java
Labels: request review

#12 설문 삭제 API 구현 (MOKA-57)
  src/main/java/com/mokaform/mokaformserver/survey/controller/SurveyController.java
  src/main/java/com/mokaform/mokaformserver/survey/domain/Survey.java
  src/main/java/com/mokaform/mokaformserver/survey/dto/response/SurveyDeleteResponse.java
  src/main/java/com/mokaform/mokaformserver/survey/service/SurveyService.java
Labels: request review

#13 내가 참여한 설문 목록 조회 API 구현 (MOKA-72)
  src/main/java/com/mokaform/mokaformserver/survey/dto/mapping/SubmittedSurveyInfoMapping.java
  src/main/java/com/mokaform/mokaformserver/survey/dto/response/SubmittedSurveyInfoResponse.java
  src/main/java/com/mokaform/mokaformserver/survey/repository/SurveyCustomRepository.java
  src/main/java/com/mokaform/mokaformserver/survey/repository/SurveyCustomRepositoryImpl.java
  src/main/java/com/mokaform/mokaformserver/survey/service/SurveyService.java
  src/main/java/com/mokaform/mokaformserver/user/controller/UserController.java
Labels: request review

#17 내가 참여한 설문 답변 상세 조회 API 구현 (MOKA-76)
  src/main/java/com/mokaform/mokaformserver/answer/dto/mapping/AnswerInfoMapping.java
  src/main/java/com/mokaform/mokaformserver/answer/dto/response/AnswerDetailResponse.java
  src/main/java/com/mokaform/mokaformserver/answer/dto/response/AnswerResponse.java
  src/main/java/com/mokaform/mokaformserver/answer/dto/response/EssayAnswerResponse.java
  src/main/java/com/mokaform/mokaformserver/answer/dto/response/MultipleChoiceAnswerResponse.java
  src/main/java/com/mokaform/mokaformserver/answer/dto/response/OXAnswerResponse.java
  src/main/java/com/mokaform/mokaformserver/answer/repository/AnswerCustomRepository.java
  src/main/java/com/mokaform/mokaformserver/answer/repository/AnswerCustomRepositoryImpl.java
  src/main/java/com/mokaform/mokaformserver/answer/repository/AnswerRepository.java
  src/main/java/com/mokaform/mokaformserver/answer/repository/EssayAnswerRepository.java
  src/main/java/com/mokaform/mokaformserver/answer/repository/MultipleChoiceAnswerRepository.java
  src/main/java/com/mokaform/mokaformserver/answer/repository/OXAnswerRepository.java
  src/main/java/com/mokaform/mokaformserver/answer/service/AnswerService.java
  src/main/java/com/mokaform/mokaformserver/user/controller/UserController.java
Labels: request review

#18 [HOT!] 내가 작성한 설문 목록 조회 API 응답값에 설문 카테고리 추가 (MOKA-83)
  src/main/java/com/mokaform/mokaformserver/survey/dto/response/SubmittedSurveyInfoResponse.java
  src/main/java/com/mokaform/mokaformserver/survey/service/SurveyService.java
Labels: HOT

#19 내가 참여한 설문 목록 조회 API 응답값에 응답자 수 추가 (MOKA-87)
  src/main/java/com/mokaform/mokaformserver/survey/dto/response/SubmittedSurveyInfoResponse.java
  src/main/java/com/mokaform/mokaformserver/survey/repository/SurveyCustomRepository.java
  src/main/java/com/mokaform/mokaformserver/survey/repository/SurveyCustomRepositoryImpl.java
  src/main/java/com/mokaform/mokaformserver/survey/service/SurveyService.java
Labels: HOT

#21 설문 통계 결과 조회 API 구현 (MOKA-84)
  src/main/java/com/mokaform/mokaformserver/answer/dto/mapping/EssayAnswerStatsMapping.java
  src/main/java/com/mokaform/mokaformserver/answer/dto/mapping/MultipleChoiceAnswerStatsMapping.java
  src/main/java/com/mokaform/mokaformserver/answer/dto/mapping/OXAnswerStatsMapping.java
  src/main/java/com/mokaform/mokaformserver/answer/repository/AnswerCustomRepository.java
  src/main/java/com/mokaform/mokaformserver/answer/repository/AnswerCustomRepositoryImpl.java
  src/main/java/com/mokaform/mokaformserver/answer/service/AnswerService.java
  src/main/java/com/mokaform/mokaformserver/survey/dto/response/AnswerStatsResponse.java
  src/main/java/com/mokaform/mokaformserver/user/controller/UserController.java
Labels: request review

#22 설문 통계 결과 조회 API 응답값 수정 (MOKA-92)
  src/main/java/com/mokaform/mokaformserver/answer/dto/mapping/EssayAnswerStatsMapping.java
  src/main/java/com/mokaform/mokaformserver/answer/dto/mapping/MultipleChoiceAnswerStatsMapping.java
  src/main/java/com/mokaform/mokaformserver/answer/dto/mapping/OXAnswerStatsMapping.java
  src/main/java/com/mokaform/mokaformserver/answer/repository/AnswerCustomRepositoryImpl.java
  src/main/java/com/mokaform/mokaformserver/answer/service/AnswerService.java
  src/main/java/com/mokaform/mokaformserver/survey/dto/response/AnswerStatsResponse.java
Labels: HOT

#23 이메일 중복 확인 API 구현 (MOKA-93)
  src/main/java/com/mokaform/mokaformserver/user/controller/UserController.java
  src/main/java/com/mokaform/mokaformserver/user/dto/response/DuplicateValidationResponse.java
  src/main/java/com/mokaform/mokaformserver/user/repository/UserRepository.java
  src/main/java/com/mokaform/mokaformserver/user/service/UserService.java
Labels: request review

#24 닉네임 중복 확인 API 구현 (MOKA-94)
  src/main/java/com/mokaform/mokaformserver/user/controller/UserController.java
  src/main/java/com/mokaform/mokaformserver/user/repository/UserRepository.java
  src/main/java/com/mokaform/mokaformserver/user/service/UserService.java
Labels: request review

#25 설문 통계 결과 조회 API 응답값 수정 v2
  src/main/java/com/mokaform/mokaformserver/answer/dto/mapping/EssayAnswerStatsMapping.java
  src/main/java/com/mokaform/mokaformserver/answer/dto/mapping/MultipleChoiceAnswerStatsMapping.java
  src/main/java/com/mokaform/mokaformserver/answer/dto/mapping/OXAnswerStatsMapping.java
  src/main/java/com/mokaform/mokaformserver/answer/dto/response/stat/AnswerStatsResponse.java
  src/main/java/com/mokaform/mokaformserver/answer/dto/response/stat/EssayStat.java
  src/main/java/com/mokaform/mokaformserver/answer/dto/response/stat/MultipleChoiceResult.java
  src/main/java/com/mokaform/mokaformserver/answer/dto/response/stat/MultipleChoiceStat.java
  src/main/java/com/mokaform/mokaformserver/answer/dto/response/stat/OXStat.java
  src/main/java/com/mokaform/mokaformserver/answer/dto/response/stat/QuestionInfo.java
  src/main/java/com/mokaform/mokaformserver/answer/repository/AnswerCustomRepositoryImpl.java
  src/main/java/com/mokaform/mokaformserver/answer/service/AnswerService.java
  src/main/java/com/mokaform/mokaformserver/survey/dto/response/AnswerStatsResponse.java
  src/main/java/com/mokaform/mokaformserver/user/controller/UserController.java
Labels: request review

#26 로컬 로그인 API 구현 + JWT (MOKA-50)
  .gitignore
  build.gradle
  src/main/java/com/mokaform/mokaformserver/answer/controller/AnswerController.java
  src/main/java/com/mokaform/mokaformserver/answer/service/AnswerService.java
  src/main/java/com/mokaform/mokaformserver/common/config/EmbeddedRedisConfig.java
  src/main/java/com/mokaform/mokaformserver/common/config/JwtConfig.java
  src/main/java/com/mokaform/mokaformserver/common/config/RedisConfig.java
  src/main/java/com/mokaform/mokaformserver/common/config/WebSecurityConfig.java
  src/main/java/com/mokaform/mokaformserver/common/exception/errorcode/CommonErrorCode.java
  src/main/java/com/mokaform/mokaformserver/common/exception/errorcode/SurveyErrorCode.java
  src/main/java/com/mokaform/mokaformserver/common/exception/errorcode/UserErrorCode.java
  src/main/java/com/mokaform/mokaformserver/common/jwt/ExceptionHandlerFilter.java
  src/main/java/com/mokaform/mokaformserver/common/jwt/Jwt.java
  src/main/java/com/mokaform/mokaformserver/common/jwt/JwtAuthentication.java
  src/main/java/com/mokaform/mokaformserver/common/jwt/JwtAuthenticationFilter.java
  src/main/java/com/mokaform/mokaformserver/common/jwt/JwtAuthenticationProvider.java
  src/main/java/com/mokaform/mokaformserver/common/jwt/JwtAuthenticationToken.java
  src/main/java/com/mokaform/mokaformserver/common/util/RedisService.java
  src/main/java/com/mokaform/mokaformserver/common/util/SurveyUtilService.java
  src/main/java/com/mokaform/mokaformserver/common/util/UserUtilService.java
  src/main/java/com/mokaform/mokaformserver/survey/controller/SurveyController.java
  src/main/java/com/mokaform/mokaformserver/survey/service/SurveyService.java
  src/main/java/com/mokaform/mokaformserver/user/controller/UserController.java
  src/main/java/com/mokaform/mokaformserver/user/domain/Role.java
  src/main/java/com/mokaform/mokaformserver/user/domain/User.java
  src/main/java/com/mokaform/mokaformserver/user/domain/enums/RoleName.java
  src/main/java/com/mokaform/mokaformserver/user/dto/request/LocalLoginRequest.java
  src/main/java/com/mokaform/mokaformserver/user/dto/request/LoginRequest.java
  src/main/java/com/mokaform/mokaformserver/user/dto/response/LocalLoginResponse.java
  src/main/java/com/mokaform/mokaformserver/user/dto/response/LoginResponse.java
  src/main/java/com/mokaform/mokaformserver/user/repository/RoleRepository.java
  src/main/java/com/mokaform/mokaformserver/user/repository/UserRepository.java
  src/main/java/com/mokaform/mokaformserver/user/service/UserService.java
  src/main/resources/application-local.yml
Labels: request review

#27 나의 정보 조회 API 구현 (MOKA-109)
  src/main/java/com/mokaform/mokaformserver/user/controller/UserController.java
  src/main/java/com/mokaform/mokaformserver/user/dto/response/UserGetResponse.java
  src/main/java/com/mokaform/mokaformserver/user/repository/PreferenceCategoryRepository.java
  src/main/java/com/mokaform/mokaformserver/user/service/UserService.java
Labels: request review

#28 내가 참여한 설문 목록 조회 API 에러 수정 (MOKA-116)
  src/main/java/com/mokaform/mokaformserver/survey/repository/SurveyCustomRepositoryImpl.java
Labels: HOT

#29 JWT 토큰 관리 (MOKA-111)
  src/main/java/com/mokaform/mokaformserver/common/config/JwtConfig.java
  src/main/java/com/mokaform/mokaformserver/common/config/WebSecurityConfig.java
  src/main/java/com/mokaform/mokaformserver/common/exception/AuthException.java
  src/main/java/com/mokaform/mokaformserver/common/exception/errorcode/CommonErrorCode.java
  src/main/java/com/mokaform/mokaformserver/common/jwt/ExceptionHandlerFilter.java
  src/main/java/com/mokaform/mokaformserver/common/jwt/Jwt.java
  src/main/java/com/mokaform/mokaformserver/common/jwt/JwtAuthenticationFilter.java
  src/main/java/com/mokaform/mokaformserver/common/jwt/JwtAuthenticationProvider.java
  src/main/java/com/mokaform/mokaformserver/common/jwt/JwtService.java
  src/main/java/com/mokaform/mokaformserver/common/util/constant/RedisConstants.java
  src/main/java/com/mokaform/mokaformserver/user/controller/UserController.java
  src/main/java/com/mokaform/mokaformserver/user/dto/request/TokenReissueRequest.java
Labels: request review

#30 유저 정보 조회 API response에 userId 추가
  src/main/java/com/mokaform/mokaformserver/user/dto/response/UserGetResponse.java
Labels: HOT

#31 Swagger 설명 추가
  src/main/java/com/mokaform/mokaformserver/answer/controller/AnswerController.java
  src/main/java/com/mokaform/mokaformserver/common/config/SwaggerConfig.java
  src/main/java/com/mokaform/mokaformserver/survey/controller/SurveyController.java
  src/main/java/com/mokaform/mokaformserver/user/controller/UserController.java
Labels: HOT
